services:
  web:
    build:
      context: .
      target: production
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      NEXT_TELEMETRY_DISABLED: "1"

  dev:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    environment:
      NEXT_TELEMETRY_DISABLED: "1"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    profiles:
      - dev
